### ISSUE TITLE
SVD allowing smaller matrices

### ISSUE THREAD

**Issue by NicolasL-S** [Algopaul/KWLinalg#4]
Your package is terrific. For my needs tho, there is the issue that I don't know in advance the size of my matrix. 

Could it be possible to make it so that

```
f = svd_functor_divconquer(m, n, Float64)
svdA = f(A)
```

allows for A matrices at most m x n, but maybe smaller? The resulting svdA.U, svdA.S and svdA.Vt would be the proper size corresponding to A, but written inside the initial allocated memory space. Right now, I would have to generate a new svd_functor_divconquer(m, n, Float64) for any new possible (m,n) I may encounter which actually makes svd! more usable.

**Comment by Algopaul** [comment]
Thank you for opening this issue. This is a good idea! I added your feature **for real matrices only** (since this seems to be your use-case) but did not have time to do a proper evaluation of the consequences of my modification to the runtime or add the feature also for complex matrices. I will revisit this at a later time and also add support for complex matrices then.

**Comment by NicolasL-S** [comment]
That was quick! I've checked your example (and it works of course) and it seems to take the exact same time with
svd_functor_divconquer(m+1, n+1, Float64) 
as with
svd_functor_divconquer(m, n, Float64)

By the way, It is for an optimization package and I've got requests to make it work for complex numbers as well. So if you have time to do it eventually and register the new version on Julia Hub, that would be awesome.

Thanks a lot.
